### ISSUE TITLE
Working on Cervantes 4?

### ISSUE THREAD

**Issue by rmgui** [bq/cervantes#7]
I'm wondering if the firmware is able to run on the bq Cervantes 4? In addition, I'ld appreciate if the developer(s) could add a list of devices on which this firmware runs to the README file.

**Comment by pavlo97** [comment]
Hello, yes, it runs in Cervantes 4 also. For extended info please see https://blog.bq.com/es/bq-ereaders-developers-program/, devices list is included there.
